apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-argocd
  namespace: argocd
spec:
  destination:
    namespace: sample-argocd
    server: https://kubernetes.default.svc
  project: sample-project
  source:
    path: ./
    repoURL: https://github.com/alguacilaguamara/GitOps-example.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
