apiVersion: v1
kind: Service
metadata:
  name: canary-demo-preview
  namespace: rollout
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: canary-demo